server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.16.10.142:3306/iuuui_mysql_backup?useunicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: iuuui
      password: iuuui12345.
